version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: "newsletter-database"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - newsletter
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build:
      context: ./back
    container_name: "newsletter-rest-api"
    environment:
      HTTP_PORT: "8080"
      FRONTEND_URL: "http://localhost:3001"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
      ACCESS_TOKEN_PRIVATE_KEY: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDV3dJQkFBS0JnR0N4Y25TTlF5SE1STnJzOFJHdG9wWkpIRnZnMnY4Y2I2YWpFRVNWajlPd3krMUxjKzM0CklyK1pJQWNXSkFJZ2FPZUU3MFJucy9HQ0lMeDJQY0EySElMR284VElwN3BaZXdPNEh4dFBqRkxsRS9wbHJIU20Kc3BZWUE0R3BpMVkvcHgvMlJFR2x5U0RYR1VxQUxlM2s5c2JreW1xK1Y3eTRhaVlZc3FmQXFhd2xBZ01CQUFFQwpnWUFFeHA3MW5NaVZFY2JRM1dVbXoyRzVkSkQvQk1Nc1dKWTNMOVNzM29wRkZYVnRHZzMyMGd1OVZPM2RDNzNwCmtQbzlmVFpvTllzUXdiR21QVnpkY283RDQwZjBFLzFrbjNNdlk1bVdvOU1zRFR2UUI3cGhESW84eG51TjdwRE4KUkdFbzJ6K2wvOFVKWVRaR0lnK0R3SWl2d1RDbUJwTTN6RGlmRUplZkVHSXVJUUpCQUtPbEV6UFlXZGFtVXdyOQpybHJ4aG5EZkNsVXU4REV3cW5xWDd0UzlkMUd5QmxvZzVTNUJaRHJORDVHdEYzTENPb2txVlZIbkJrdmpJTDhpClRQMmFmL2tDUVFDWFEyUUF1WUE4bmphQmptTDFRSkpmZjBIZ0RyeDFQMkpzY0s1c01lMWpTV0w0RXlFS1k2bHoKd1JkbFVWSnl6YUtYT1ZXZmx1R21KYzFYSXhYZ3hyQ05Ba0JSOWdQQUc4UWpOZnF4cm96OUQ2citMVGZIb2xLNgowRjBTT2JaczV0ZzBHcTREeGlZREhNMU9oaFllS0V0dU5zbUttYUZSL0J1ek5uYllSQjI3aHY1QkFrQkJSc25QCkxqNVM2b3ZuR1FWSGhWZ2xjZ3VCbjVwZ2xydm94Qy9oYlNKZXFIclhSNW9JbTcyeXdHOVNQK2Z1dHlNbFU0N0oKMGhrSzFHRnE2eTh6MDBxNUFrRUFqc2s2Uml3OFF6UzdrNit4YkZEZHFLWkdkbUpoVm9IbEEzR3VXMUEzVGNJKwpEVmJMR3lWUHh1R20wRDA3NHpOQUxaY0NoZzBkMGQzT3NTZzJKSjdWWnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="
      ACCESS_TOKEN_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZU1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTUFEQ0JpQUtCZ0dDeGNuU05ReUhNUk5yczhSR3RvcFpKSEZ2ZwoydjhjYjZhakVFU1ZqOU93eSsxTGMrMzRJcitaSUFjV0pBSWdhT2VFNzBSbnMvR0NJTHgyUGNBMkhJTEdvOFRJCnA3cFpld080SHh0UGpGTGxFL3BsckhTbXNwWVlBNEdwaTFZL3B4LzJSRUdseVNEWEdVcUFMZTNrOXNia3ltcSsKVjd5NGFpWVlzcWZBcWF3bEFnTUJBQUU9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=="
      ACCESS_TOKEN_EXPIRED_IN: "43800m"
      AWS_S3_BUCKET: ""
      AWS_S3_REGION: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - newsletter
  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: http://backend:8080
    container_name: "newsletter-front"
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - newsletter
volumes:
  database_postgres:

networks:
  newsletter:
    driver: bridge
