version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: "newsletter-database"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - newsletter
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build:
      context: ./back
    container_name: "newsletter-rest-api"
    environment:
      HTTP_PORT: "8080"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
      ACCESS_TOKEN_PRIVATE_KEY: ""
      ACCESS_TOKEN_PUBLIC_KEY: ""
      ACCESS_TOKEN_EXPIRED_IN: "43800m"
      AWS_S3_ACCESS_KEY_ID: ""
      AWS_S3_BUCKET: ""
      AWS_S3_REGION: ""
      AWS_S3_SECRET_ACCESS_KEY: ""
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - newsletter
  front:
      build:
        context: ./front
      container_name: "newsletter-front"
      environment:
        NEXT_PUBLIC_API_URL: "http://127.0.0.1:8080/api/"
      ports:
        - "3000:3000"
      depends_on:
        - api
      networks:
        - newsletter
volumes:
  database_postgres:

networks:
  newsletter:
    driver: bridge
